export const nativeCopy = {
  ko: {
    loading: '기기 데이터를 읽고 있어요…', retry: '다시 읽기',
    phase: '앱 전환 3단계 · 개발용',
    chooseArea: '지역을 직접 선택해 주세요',
    selectArea: '대한민국 → 서울 → 성수동 선택',
    changeArea: '다른 지역 선택',
    oneArea: '현재 데모는 성수동만 제공합니다. 기기 언어나 위치로 지역을 정하지 않습니다.',
    nativeStorage: '앱 데이터 삭제·앱 제거·기기 변경 시 기록을 잃을 수 있습니다. 기기 내 비암호화 저장이며 계정·인증·동기화가 아닙니다.',
    nativeSaveError: '앱 저장에 실패했습니다. 저장 완료로 처리하지 않았습니다. 기존 데이터를 다시 읽은 뒤 재시도해 주세요.',
    savedTrips: '앱에 저장된 여행', unverified: '예시 콘텐츠 · 미검증',
    source: '원문 언어', savedLanguage: '언어 설정을 이 기기에 저장했습니다.',
    createTripHelp: '지역은 직접 선택한 성수동으로 저장합니다. 일정과 메모는 비공개이며 이 앱 안에만 저장됩니다.',
    tripSaved: '비공개 여행을 이 앱에 저장했습니다.', tripOpen: '일정 보기', tripDates: '여행 기간',
    backTrips: '여행 목록', addSaved: '유닛 버전 스냅샷을 일정에 저장했습니다.',
    selectTripFirst: '유닛을 담을 비공개 여행을 선택해 주세요.', scheduleSaved: '일정 변경을 저장했습니다.',
    recordSaved: '직접 체크한 경험과 개인 메모를 저장했습니다.', scheduleSource: '담은 원문 버전',
    manualPlan: '이동·휴식은 직접 입력한 예상 시간이며 실제 위치나 경로가 아닙니다.',
    discardTitle: '저장하지 않은 변경이 있어요', discardBody: '지금 나가면 입력한 변경 내용이 사라집니다.',
    keepEditing: '계속 작성', discard: '변경 버리기', checkOn: '체크됨', checkOff: '체크 안 됨',
    skipSave: '건너뜀으로 저장', noNativeUnits: '이 여행에는 아직 담은 유닛이 없습니다.',
    privateOnly: '비공개 · 이 앱에만 저장', currentStatus: '현재 상태', chooseAnotherTrip: '다른 여행 선택',
    backupTitle: '로컬 백업·복원',
    backupPrivacy: '백업 파일에는 비공개 여행, 정확한 일정, 개인 메모가 포함됩니다. 암호화되지 않으므로 안전한 폴더에 보관하세요.',
    backupNoUpload: '앱이 백업을 서버로 보내지 않습니다. 내보내기·가져오기는 시스템 파일 선택기를 직접 눌렀을 때만 열립니다.',
    exportBackup: '백업 파일 내보내기', importBackup: '백업 파일 가져오기', backupPreview: '가져오기 미리보기',
    backupFile: '선택한 파일', backupSource: '형식', backupCurrent: 'Yamone Trip 백업 v1', backupLegacy: '이전 로컬 데이터 v1',
    backupCreated: '생성 시각', backupUnknownDate: '기록 없음', backupCounts: '여행 / 일정 유닛 / 경험 기록',
    backupReplaceWarning: '확인하면 현재 이 앱의 모든 로컬 데이터가 미리보기의 데이터로 교체됩니다. 파일은 수정하거나 삭제하지 않습니다.',
    confirmImport: '검증된 백업으로 교체', backupExported: '선택한 폴더에 백업 파일을 저장했습니다.',
    backupImported: '검증된 백업을 이 앱에 복원했습니다.', backupInvalid: '파일 전체를 검증하지 못했습니다. 현재 데이터는 변경하지 않았습니다.',
    backupVersion: '지원하지 않는 백업 버전입니다. 파일과 현재 데이터는 변경하지 않았습니다.',
    backupTooLarge: '백업 파일이 비어 있거나 10MB 제한을 넘었습니다. 현재 데이터는 변경하지 않았습니다.',
    backupError: '파일 작업을 완료하지 못했습니다. 현재 데이터는 변경하지 않았습니다.',
  },
  en: {
    loading: 'Reading device data…', retry: 'Reload data',
    phase: 'Native app migration 3 · Development build',
    chooseArea: 'Select an area manually',
    selectArea: 'Select South Korea → Seoul → Seongsu',
    changeArea: 'Change area',
    oneArea: 'Only Seongsu is available in this demo. Device language and location do not choose your area.',
    nativeStorage: 'Clearing app data, uninstalling or changing devices can lose records. Storage is unencrypted and local, not an account, authentication or sync.',
    nativeSaveError: 'App storage failed. The change was not marked as saved. Reload existing data before trying again.',
    savedTrips: 'Trips stored in this app', unverified: 'Example content · Unverified',
    source: 'Original language', savedLanguage: 'Language preference saved on this device.',
    createTripHelp: 'The area is the manually selected Seongsu demo. Itinerary and notes are private and saved only in this app.',
    tripSaved: 'Private trip saved in this app.', tripOpen: 'View itinerary', tripDates: 'Trip dates',
    backTrips: 'Trip list', addSaved: 'Unit-version snapshot saved to the itinerary.',
    selectTripFirst: 'Choose a private trip for this unit.', scheduleSaved: 'Schedule changes saved.',
    recordSaved: 'Self-checked experience and private note saved.', scheduleSource: 'Saved source version',
    manualPlan: 'Travel and break times are your manual estimates, not a location or route.',
    discardTitle: 'You have unsaved changes', discardBody: 'Leaving now will discard what you entered.',
    keepEditing: 'Keep editing', discard: 'Discard changes', checkOn: 'Checked', checkOff: 'Not checked',
    skipSave: 'Save as skipped', noNativeUnits: 'No units are scheduled in this trip yet.',
    privateOnly: 'Private · Saved only in this app', currentStatus: 'Current status', chooseAnotherTrip: 'Choose another trip',
    backupTitle: 'Local backup and restore',
    backupPrivacy: 'A backup contains private trips, exact schedules and personal notes. It is not encrypted, so keep it in a safe folder.',
    backupNoUpload: 'The app does not upload backups. Export and import open the system file picker only after you tap them.',
    exportBackup: 'Export backup file', importBackup: 'Import backup file', backupPreview: 'Import preview',
    backupFile: 'Selected file', backupSource: 'Format', backupCurrent: 'Yamone Trip backup v1', backupLegacy: 'Earlier local data v1',
    backupCreated: 'Created', backupUnknownDate: 'Not recorded', backupCounts: 'Trips / scheduled units / experience records',
    backupReplaceWarning: 'Confirming replaces all local data in this app with the previewed data. The selected file is not changed or deleted.',
    confirmImport: 'Replace with validated backup', backupExported: 'Backup file saved in the selected folder.',
    backupImported: 'Validated backup restored in this app.', backupInvalid: 'The entire file could not be validated. Current data was not changed.',
    backupVersion: 'This backup version is unsupported. The file and current data were not changed.',
    backupTooLarge: 'The backup is empty or exceeds the 10 MB limit. Current data was not changed.',
    backupError: 'The file operation could not be completed. Current data was not changed.',
  },
};
