export const nativeCopy = {
  ko: {
    loading: '기기 데이터를 읽고 있어요…', retry: '다시 읽기',
    phase: '앱 전환 7단계 · 개발용',
    chooseArea: '지역을 직접 선택해 주세요',
    selectArea: '대한민국 → 서울 → 성수동 선택',
    changeArea: '다른 지역 선택',
    oneArea: '현재 데모는 성수동만 제공합니다. 기기 언어나 위치로 지역을 정하지 않습니다.',
    nativeStorage: '앱 데이터 삭제·앱 제거·기기 변경 시 기록을 잃을 수 있습니다. 기기 내 비암호화 저장이며 계정·인증·동기화가 아닙니다.',
    nativeSaveError: '앱 저장에 실패했습니다. 저장 완료로 처리하지 않았습니다. 기존 데이터를 다시 읽은 뒤 재시도해 주세요.',
    savedTrips: '앱에 저장된 여행', unverified: '예시 콘텐츠 · 미검증',
    source: '원문 언어', savedLanguage: '언어 설정을 이 기기에 저장했습니다.',
    createTripHelp: '지역은 직접 선택한 성수동으로 저장합니다. 일정과 메모는 비공개이며 이 앱 안에만 저장됩니다.',
    tripSaved: '비공개 여행을 이 앱에 저장했습니다.', tripOpen: '일정 보기', tripDates: '여행 기간',
    backTrips: '여행 목록', addSaved: '유닛 버전 스냅샷을 일정에 저장했습니다.',
    selectTripFirst: '유닛을 담을 비공개 여행을 선택해 주세요.', scheduleSaved: '일정 변경을 저장했습니다.',
    recordSaved: '직접 체크한 경험과 개인 메모를 저장했습니다.', scheduleSource: '담은 원문 버전',
    manualPlan: '이동·휴식은 직접 입력한 예상 시간이며 실제 위치나 경로가 아닙니다.',
    discardTitle: '저장하지 않은 변경이 있어요', discardBody: '지금 나가면 입력한 변경 내용이 사라집니다.',
    keepEditing: '계속 작성', discard: '변경 버리기', checkOn: '체크됨', checkOff: '체크 안 됨',
    skipSave: '건너뜀으로 저장', noNativeUnits: '이 여행에는 아직 담은 유닛이 없습니다.',
    privateOnly: '비공개 · 이 앱에만 저장', currentStatus: '현재 상태', chooseAnotherTrip: '다른 여행 선택',
    backupTitle: '로컬 백업·복원',
    backupPrivacy: '백업 파일에는 비공개 여행, 정확한 일정, 개인 메모가 포함됩니다. 암호화되지 않으므로 안전한 폴더에 보관하세요.',
    backupNoUpload: '앱이 백업을 서버로 보내지 않습니다. 내보내기·가져오기는 시스템 파일 선택기를 직접 눌렀을 때만 열립니다.',
    exportBackup: '백업 파일 내보내기', importBackup: '백업 파일 가져오기', backupPreview: '가져오기 미리보기',
    backupFile: '선택한 파일', backupSource: '형식', backupCurrent: 'Yamone Trip 백업 v1', backupLegacy: '이전 로컬 데이터 v1', backupRaw: '로컬 원시 데이터',
    backupCreated: '생성 시각', backupUnknownDate: '기록 없음', backupCounts: '여행 / 일정 유닛 / 경험 기록', backupAuthorCounts: '로컬 유닛 / 저장된 초안 / 개선 제안 / 번역',
    backupReplaceWarning: '확인하면 현재 이 앱의 모든 로컬 데이터가 미리보기의 데이터로 교체됩니다. 파일은 수정하거나 삭제하지 않습니다.',
    confirmImport: '검증된 백업으로 교체', backupExported: '선택한 폴더에 백업 파일을 저장했습니다.',
    backupImported: '검증된 백업을 이 앱에 복원했습니다.', backupInvalid: '파일 전체를 검증하지 못했습니다. 현재 데이터는 변경하지 않았습니다.',
    backupVersion: '지원하지 않는 백업 버전입니다. 파일과 현재 데이터는 변경하지 않았습니다.',
    backupTooLarge: '백업 파일이 비어 있거나 10MB 제한을 넘었습니다. 현재 데이터는 변경하지 않았습니다.',
    backupError: '파일 작업을 완료하지 못했습니다. 현재 데이터는 변경하지 않았습니다.',
    newLocalUnit: '새 로컬 유닛 작성', editLocalUnit: '새 불변 버전 작성',
    localPrivateUnverified: '비공개 로컬 유닛 · 미검증', localPrivateDraft: '비공개 로컬 초안',
    localUnitHelp: '현재 직접 선택한 지역에 원문을 작성합니다. 서버에 공개되지 않으며 번역도 자동 생성하지 않습니다.',
    originalLocale: '원문 언어', localeCode: '원문 언어 코드 (예: ko, en, ja)', manualRegion: '직접 선택한 지역',
    unitTitle: '유닛 제목', unitDescription: '경험 설명', unitPlace: '장소 안내', costAmount: '예상 비용', currencyCode: '통화 코드',
    authorPoints: '경험 포인트 1–5개', pointHelp: '포인트 ID는 버전이 바뀌어도 유지됩니다. 내용이 다른 새 포인트만 추가하세요.',
    point: '경험 포인트', stablePointId: '고정 ID', removePoint: '포인트 삭제', addPoint: '포인트 추가',
    immutableVersionHelp: '버전으로 저장하면 이전 버전과 이미 일정에 담긴 스냅샷은 바뀌지 않습니다. 이 작업은 공개가 아닙니다.',
    savePrivateDraft: '비공개 초안 저장', saveImmutableVersion: '불변 로컬 버전 저장',
    unitDraftSaved: '비공개 유닛 초안을 이 앱에 저장했습니다.', unitVersionSaved: '새 불변 로컬 버전을 저장했습니다. 공개된 것은 아닙니다.',
    basedOnVersion: '기준 버전', localAuthored: '사용자 작성 · 로컬 미검증', localDevice: '이 기기 로컬 작성자',
    myUnitsHelp: '이 기기에만 저장되는 유닛 초안과 버전입니다. 회원 계정이나 공개 게시물이 아닙니다.',
    savedDrafts: '저장된 비공개 초안', resumeDraft: '초안 계속 작성', savedLocalUnits: '저장된 로컬 유닛', noLocalUnits: '아직 저장된 로컬 유닛이 없습니다.',
    versionCount: '보존된 버전', createNextVersion: '새 버전 만들기', nextVersionDraftExists: '이 유닛의 새 버전 초안이 저장되어 있습니다.',
    deleteDraft: '저장된 초안 삭제', deleteDraftTitle: '비공개 초안을 삭제할까요?', deleteDraftBody: '불변 버전과 여행 일정은 유지되고 이 초안만 삭제됩니다. 이 작업은 되돌릴 수 없습니다.', unitDraftDeleted: '저장된 비공개 초안을 삭제했습니다.',
    proposeImprovement: '개선 제안 남기기', localProposal: '비공개 로컬 개선 제안', proposalSource: '제안 대상 원문',
    improvementHelp: '원문 버전을 바꾸거나 서버에 전송하지 않습니다. 나중에 서버 연결 후 제출 여부를 별도로 결정합니다.', improvementText: '구체적인 개선 내용',
    saveImprovement: '비공개 제안 저장', improvementSaved: '개선 제안을 이 앱에만 저장했습니다. 작성자에게 전송된 것은 아닙니다.', savedImprovements: '저장된 개선 제안',
    deleteImprovement: '개선 제안 삭제', deleteImprovementTitle: '이 개선 제안을 삭제할까요?', deleteImprovementBody: '원작과 파생 유닛은 유지되며 이 로컬 제안만 삭제됩니다.', improvementDeleted: '비공개 개선 제안을 삭제했습니다.',
    createDerivative: '이 버전에서 파생 유닛 만들기', derivativeDraft: '파생 유닛 초안', attributedDerivative: '출처 표시 파생 유닛 · 로컬 미검증',
    derivedFrom: '원작 출처', derivativeAttributionHelp: '파생 유닛은 새 ID를 사용하고 원작 유닛과 정확한 버전을 계속 표시합니다. 번역은 파생 유닛이 아닙니다.',
    translationEditor: '로컬 번역 편집', localTranslation: '수동 번역 · 이 앱에만 저장',
    translationIdentity: '같은 유닛·버전', translationHelp: '원문은 바뀌지 않고 외부로 전송하지 않습니다. 번역은 새 파생 유닛이 아니며, 사용자 검토는 운영자 검증을 의미하지 않습니다.',
    translationStatus: '번역 상태', translatedTitle: '번역 제목', translatedDescription: '번역 설명', translatedPlace: '번역 장소 안내',
    translatedTip: '번역 팁', translatedPoints: '번역 경험 포인트', samePointId: '원문과 같은 포인트 ID',
    saveTranslationDraft: '번역 초안 저장', markTranslationReviewed: '내가 검토한 번역으로 저장', deleteTranslation: '이 번역 삭제',
    deleteTranslationTitle: '이 로컬 번역을 삭제할까요?', deleteTranslationBody: '원문, 다른 번역, 파생 유닛과 여행 일정은 유지됩니다.',
    translationDraftSaved: '수동 번역 초안을 이 앱에 저장했습니다.', translationReviewed: '내가 검토한 수동 번역으로 저장했습니다.', translationDeleted: '로컬 번역을 삭제했습니다.',
    createTranslation: '번역 작성', editTranslation: '번역 편집', manualTranslation: '수동 번역', machineTranslation: 'AI 번역', demoTranslation: '예시 번역 · 미검증',
    draft: '초안', machine_unreviewed: 'AI 번역 · 미검수', user_reviewed: '사용자 검토', needs_review: '재검토 필요', savedTranslations: '이 버전의 저장된 번역',
  },
  en: {
    loading: 'Reading device data…', retry: 'Reload data',
    phase: 'Native app migration 7 · Development build',
    chooseArea: 'Select an area manually',
    selectArea: 'Select South Korea → Seoul → Seongsu',
    changeArea: 'Change area',
    oneArea: 'Only Seongsu is available in this demo. Device language and location do not choose your area.',
    nativeStorage: 'Clearing app data, uninstalling or changing devices can lose records. Storage is unencrypted and local, not an account, authentication or sync.',
    nativeSaveError: 'App storage failed. The change was not marked as saved. Reload existing data before trying again.',
    savedTrips: 'Trips stored in this app', unverified: 'Example content · Unverified',
    source: 'Original language', savedLanguage: 'Language preference saved on this device.',
    createTripHelp: 'The area is the manually selected Seongsu demo. Itinerary and notes are private and saved only in this app.',
    tripSaved: 'Private trip saved in this app.', tripOpen: 'View itinerary', tripDates: 'Trip dates',
    backTrips: 'Trip list', addSaved: 'Unit-version snapshot saved to the itinerary.',
    selectTripFirst: 'Choose a private trip for this unit.', scheduleSaved: 'Schedule changes saved.',
    recordSaved: 'Self-checked experience and private note saved.', scheduleSource: 'Saved source version',
    manualPlan: 'Travel and break times are your manual estimates, not a location or route.',
    discardTitle: 'You have unsaved changes', discardBody: 'Leaving now will discard what you entered.',
    keepEditing: 'Keep editing', discard: 'Discard changes', checkOn: 'Checked', checkOff: 'Not checked',
    skipSave: 'Save as skipped', noNativeUnits: 'No units are scheduled in this trip yet.',
    privateOnly: 'Private · Saved only in this app', currentStatus: 'Current status', chooseAnotherTrip: 'Choose another trip',
    backupTitle: 'Local backup and restore',
    backupPrivacy: 'A backup contains private trips, exact schedules and personal notes. It is not encrypted, so keep it in a safe folder.',
    backupNoUpload: 'The app does not upload backups. Export and import open the system file picker only after you tap them.',
    exportBackup: 'Export backup file', importBackup: 'Import backup file', backupPreview: 'Import preview',
    backupFile: 'Selected file', backupSource: 'Format', backupCurrent: 'Yamone Trip backup v1', backupLegacy: 'Earlier local data v1', backupRaw: 'Raw local data',
    backupCreated: 'Created', backupUnknownDate: 'Not recorded', backupCounts: 'Trips / scheduled units / experience records', backupAuthorCounts: 'Local units / saved drafts / improvement proposals / translations',
    backupReplaceWarning: 'Confirming replaces all local data in this app with the previewed data. The selected file is not changed or deleted.',
    confirmImport: 'Replace with validated backup', backupExported: 'Backup file saved in the selected folder.',
    backupImported: 'Validated backup restored in this app.', backupInvalid: 'The entire file could not be validated. Current data was not changed.',
    backupVersion: 'This backup version is unsupported. The file and current data were not changed.',
    backupTooLarge: 'The backup is empty or exceeds the 10 MB limit. Current data was not changed.',
    backupError: 'The file operation could not be completed. Current data was not changed.',
    newLocalUnit: 'Create local unit', editLocalUnit: 'Create immutable version',
    localPrivateUnverified: 'Private local unit · Unverified', localPrivateDraft: 'Private local draft',
    localUnitHelp: 'Write original content for the manually selected area. It is not published to a server and no translation is generated automatically.',
    originalLocale: 'Original language', localeCode: 'Original locale code (for example ko, en, ja)', manualRegion: 'Manually selected area',
    unitTitle: 'Unit title', unitDescription: 'Experience description', unitPlace: 'Place guidance', costAmount: 'Estimated cost', currencyCode: 'Currency code',
    authorPoints: '1–5 experience points', pointHelp: 'Point IDs remain stable across versions. Add a new ID only for a genuinely new point.',
    point: 'Experience point', stablePointId: 'Stable ID', removePoint: 'Remove point', addPoint: 'Add point',
    immutableVersionHelp: 'Saving a version never changes earlier versions or snapshots already in trips. This does not publish anything.',
    savePrivateDraft: 'Save private draft', saveImmutableVersion: 'Save immutable local version',
    unitDraftSaved: 'Private unit draft saved in this app.', unitVersionSaved: 'New immutable local version saved. It was not published.',
    basedOnVersion: 'Based on version', localAuthored: 'User-authored · Local unverified', localDevice: 'Local author on this device',
    myUnitsHelp: 'Unit drafts and versions saved only in this app. They are not an account or public posts.',
    savedDrafts: 'Saved private drafts', resumeDraft: 'Continue draft', savedLocalUnits: 'Saved local units', noLocalUnits: 'No local units saved yet.',
    versionCount: 'Preserved versions', createNextVersion: 'Create new version', nextVersionDraftExists: 'A next-version draft is already saved for this unit.',
    deleteDraft: 'Delete saved draft', deleteDraftTitle: 'Delete this private draft?', deleteDraftBody: 'Immutable versions and trip schedules remain. Only this draft is deleted, and this cannot be undone.', unitDraftDeleted: 'Saved private draft deleted.',
    proposeImprovement: 'Propose an improvement', localProposal: 'Private local improvement proposal', proposalSource: 'Proposal source',
    improvementHelp: 'This does not change the source version or send anything to a server. Submission can be decided separately after a backend is connected.', improvementText: 'Concrete improvement',
    saveImprovement: 'Save private proposal', improvementSaved: 'Improvement saved only in this app. It was not sent to the author.', savedImprovements: 'Saved improvement proposals',
    deleteImprovement: 'Delete improvement', deleteImprovementTitle: 'Delete this improvement proposal?', deleteImprovementBody: 'The original and derivative units remain. Only this local proposal is deleted.', improvementDeleted: 'Private improvement proposal deleted.',
    createDerivative: 'Create derivative from this version', derivativeDraft: 'Derivative unit draft', attributedDerivative: 'Attributed derivative · Local unverified',
    derivedFrom: 'Derived from', derivativeAttributionHelp: 'A derivative gets a new ID and keeps the exact original unit/version attribution. A translation is not a derivative.',
    translationEditor: 'Edit local translation', localTranslation: 'Manual translation · Saved only in this app',
    translationIdentity: 'Same unit and version', translationHelp: 'The original is unchanged and nothing is sent externally. A translation is not a new derivative unit, and user review does not mean administrator verification.',
    translationStatus: 'Translation status', translatedTitle: 'Translated title', translatedDescription: 'Translated description', translatedPlace: 'Translated place guidance',
    translatedTip: 'Translated tip', translatedPoints: 'Translated experience points', samePointId: 'Same point ID as original',
    saveTranslationDraft: 'Save translation draft', markTranslationReviewed: 'Save as reviewed by me', deleteTranslation: 'Delete this translation',
    deleteTranslationTitle: 'Delete this local translation?', deleteTranslationBody: 'The original, other translations, derivatives and trip schedules remain unchanged.',
    translationDraftSaved: 'Manual translation draft saved in this app.', translationReviewed: 'Saved as a manual translation reviewed by you.', translationDeleted: 'Local translation deleted.',
    createTranslation: 'Create translation', editTranslation: 'Edit translation', manualTranslation: 'Manual translation', machineTranslation: 'AI translation', demoTranslation: 'Example translation · Unverified',
    draft: 'Draft', machine_unreviewed: 'AI translation · Unreviewed', user_reviewed: 'User reviewed', needs_review: 'Needs review', savedTranslations: 'Saved translations for this version',
  },
};
