export const nativeCopy = {
  ko: {
    loading: '기기 데이터를 읽고 있어요…', retry: '다시 읽기',
    phase: '앱 전환 2단계 · 개발용',
    chooseArea: '지역을 직접 선택해 주세요',
    selectArea: '대한민국 → 서울 → 성수동 선택',
    changeArea: '다른 지역 선택',
    oneArea: '현재 데모는 성수동만 제공합니다. 기기 언어나 위치로 지역을 정하지 않습니다.',
    nativeStorage: '앱 데이터 삭제·앱 제거·기기 변경 시 기록을 잃을 수 있습니다. 기기 내 비암호화 저장이며 계정·인증·동기화가 아닙니다. 백업 기능은 아직 없습니다.',
    nativeSaveError: '앱 저장에 실패했습니다. 저장 완료로 처리하지 않았습니다. 기존 데이터를 다시 읽은 뒤 재시도해 주세요.',
    savedTrips: '앱에 저장된 여행', unverified: '예시 콘텐츠 · 미검증',
    source: '원문 언어', savedLanguage: '언어 설정을 이 기기에 저장했습니다.',
    createTripHelp: '지역은 직접 선택한 성수동으로 저장합니다. 일정과 메모는 비공개이며 이 앱 안에만 저장됩니다.',
    tripSaved: '비공개 여행을 이 앱에 저장했습니다.', tripOpen: '일정 보기', tripDates: '여행 기간',
    backTrips: '여행 목록', addSaved: '유닛 버전 스냅샷을 일정에 저장했습니다.',
    selectTripFirst: '유닛을 담을 비공개 여행을 선택해 주세요.', scheduleSaved: '일정 변경을 저장했습니다.',
    recordSaved: '직접 체크한 경험과 개인 메모를 저장했습니다.', scheduleSource: '담은 원문 버전',
    manualPlan: '이동·휴식은 직접 입력한 예상 시간이며 실제 위치나 경로가 아닙니다.',
    discardTitle: '저장하지 않은 변경이 있어요', discardBody: '지금 나가면 입력한 변경 내용이 사라집니다.',
    keepEditing: '계속 작성', discard: '변경 버리기', checkOn: '체크됨', checkOff: '체크 안 됨',
    skipSave: '건너뜀으로 저장', noNativeUnits: '이 여행에는 아직 담은 유닛이 없습니다.',
    privateOnly: '비공개 · 이 앱에만 저장', currentStatus: '현재 상태', chooseAnotherTrip: '다른 여행 선택',
  },
  en: {
    loading: 'Reading device data…', retry: 'Reload data',
    phase: 'Native app migration 2 · Development build',
    chooseArea: 'Select an area manually',
    selectArea: 'Select South Korea → Seoul → Seongsu',
    changeArea: 'Change area',
    oneArea: 'Only Seongsu is available in this demo. Device language and location do not choose your area.',
    nativeStorage: 'Clearing app data, uninstalling or changing devices can lose records. Storage is unencrypted and local, not an account, authentication or sync. Backup is not available yet.',
    nativeSaveError: 'App storage failed. The change was not marked as saved. Reload existing data before trying again.',
    savedTrips: 'Trips stored in this app', unverified: 'Example content · Unverified',
    source: 'Original language', savedLanguage: 'Language preference saved on this device.',
    createTripHelp: 'The area is the manually selected Seongsu demo. Itinerary and notes are private and saved only in this app.',
    tripSaved: 'Private trip saved in this app.', tripOpen: 'View itinerary', tripDates: 'Trip dates',
    backTrips: 'Trip list', addSaved: 'Unit-version snapshot saved to the itinerary.',
    selectTripFirst: 'Choose a private trip for this unit.', scheduleSaved: 'Schedule changes saved.',
    recordSaved: 'Self-checked experience and private note saved.', scheduleSource: 'Saved source version',
    manualPlan: 'Travel and break times are your manual estimates, not a location or route.',
    discardTitle: 'You have unsaved changes', discardBody: 'Leaving now will discard what you entered.',
    keepEditing: 'Keep editing', discard: 'Discard changes', checkOn: 'Checked', checkOff: 'Not checked',
    skipSave: 'Save as skipped', noNativeUnits: 'No units are scheduled in this trip yet.',
    privateOnly: 'Private · Saved only in this app', currentStatus: 'Current status', chooseAnotherTrip: 'Choose another trip',
  },
};
