import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { startServer } from './serve.mjs';
const require=createRequire(import.meta.url);
let chromium;
try { ({chromium}=require('playwright')); }
catch {
  if (!process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES) throw new Error('UI tests need a local Playwright installation and Chromium. See README.');
  ({chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright'));
}
const browser=await chromium.launch({headless:true});
const server=await startServer(0); const origin=`http://127.0.0.1:${server.address().port}`;
await mkdir('test-results',{recursive:true});
let scenarios=0;
const errors=[],external=[];
try {
  const context=await browser.newContext({locale:'ko-KR',viewport:{width:390,height:844}});
  const page=await context.newPage();
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  page.on('request',request=>{if(!request.url().startsWith(origin)&&!request.url().startsWith('data:'))external.push(request.url());});
  await page.goto(origin);
  assert.equal(await page.locator('html').getAttribute('lang'),'ko');
  assert.equal(await page.locator('.unit-card').count(),4); scenarios++;
  await page.screenshot({path:'test-results/discover-mobile.png',fullPage:true});
  await page.locator('[name=query]').fill('forest'); assert.equal(await page.locator('.unit-card').count(),1);
  await page.locator('[data-action=reset]').click();
  await page.locator('[name=maxCost]').selectOption('0'); assert.equal(await page.locator('.unit-card').count(),3); scenarios++;
  await page.locator('[data-action=reset]').click();
  await page.locator('[data-id=alley-photo]').first().click();
  await page.locator('[data-action=original]').click(); assert.equal(await page.locator('h1').getAttribute('lang'),'en');
  await page.locator('[data-action=original]').click(); assert.equal(await page.locator('h1').getAttribute('lang'),'ko'); scenarios++;
  await page.locator('[data-action=back-discover]').first().click();
  await page.locator('[data-id=forest-walk]').first().click();
  await page.locator('[data-action=add]').click();
  await page.locator('[name=name]').fill('나의 성수 여행');
  await page.locator('[name=startDate]').fill('2026-10-01'); await page.locator('[name=endDate]').fill('2026-10-03');
  await page.locator('#trip-form [type=submit]').click();
  await page.locator('#add-form [type=submit]').click();
  assert.equal(await page.locator('.schedule-card').count(),1); scenarios++;
  await page.locator('[data-action=experience]').click();
  for (const checkbox of await page.locator('[name=point]').all()) await checkbox.check();
  await page.locator('[name=note]').fill('<img src=x onerror=alert(1)> 좋은 시간');
  await page.locator('#record-form [type=submit]').click();
  assert.equal(await page.locator('.status').textContent(),'완료'); scenarios++;
  await page.reload(); await page.locator('[data-page=trips]').click();
  assert.equal(await page.locator('.status').textContent(),'완료');
  await page.locator('[data-action=experience]').click();
  assert.match(await page.locator('[name=note]').inputValue(),/<img/);assert.equal(await page.locator('.detail-card img').count(),0); scenarios++;
  await page.locator('[data-action=back-trips]').click();
  await page.screenshot({path:'test-results/trip-mobile.png',fullPage:true});
  await page.locator('#header-language').selectOption('en');
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.equal(await page.locator('.status').textContent(),'Complete');
  await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'en'); scenarios++;
  await page.locator('[data-id=forest-walk]').first().click();await page.locator('[data-action=add]').click();await page.locator('#add-form [type=submit]').click();
  assert.equal(await page.locator('.warning').count(),1); scenarios++;
  await page.locator('[data-page=discover]').click();await page.setViewportSize({width:320,height:720});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px horizontal overflow');
  await page.screenshot({path:'test-results/discover-small-en.png',fullPage:true}); scenarios++;
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'test-results/discover-desktop.png',fullPage:true});
  await context.close();
  const broken=await browser.newContext();await broken.addInitScript(()=>localStorage.setItem('yamone-trip:state:v1','{broken'));
  const brokenPage=await broken.newPage();await brokenPage.goto(origin);assert.equal(await brokenPage.locator('[role=alert]').count(),1);
  await brokenPage.locator('#header-language').selectOption('ko');assert.equal(await brokenPage.evaluate(()=>localStorage.getItem('yamone-trip:state:v1')),'{broken');await broken.close();scenarios++;
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  console.log(`PASS: ${scenarios} browser scenarios; ko/en, search, trip creation, completion, reload, escaping, conflicts, narrow layout and corrupt storage. No browser errors or external requests.`);
} finally { await browser.close(); await new Promise(resolve=>server.close(resolve)); }
